repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
      -   id: no-commit-to-branch
          args: [--branch, develop, --branch, main, --branch, master]
  -   repo: local
      hooks:
      -   id: flake8
          name: Run flake8
          entry: make lint
          language: system
          types: [python]
  -   repo: local
      hooks:
      -   id: unit-tests
          name: Run etl unit tests
          entry: make unit-test
          language: system
          types: [python]
